### ISSUE TITLE
Totally not what I expected, everything stopped started downloading, completed files became 0% and missing

### ISSUE THREAD

**Issue by Owyn** [rumanzo/bt2qbt#33] opened 2021-11-16 15:42 UTC
**Describe the bug**
Totally not what I expected, every stopped in uTorrent torrent started downloading when I opened qBitTorrent, completed torrents (which I already deleted files for) became 0% and missing error, it started checking all files

**To Reproduce**
- import from uTorrent

**Expected behavior**
All should be the same in QbitTorrent as you have left it in uTorrent

**Desktop (please complete the following information):**
 - OS: Win 10
 - uTorrent 2.2.1
 - Qbittorrent 4.3.9
 
 Here in uT:
 
![image](https://user-images.githubusercontent.com/1309656/142018618-14a9cd3c-5f7a-4602-8771-beed256104d4.png)

After importing to QT: 
![image](https://user-images.githubusercontent.com/1309656/142018881-5d486d97-41ed-4ba3-9627-c23c25f159ad.png)

 
Torrents which started by themselves after importing were stopped in uTorrent with this status, but import changed stopped to started for those: 
![image](https://user-images.githubusercontent.com/1309656/142018077-e7d3a6c7-83ef-4149-9345-8a1954621a47.png)

**Comment by rumanzo** [comment] 2021-11-16 15:55
This all extremely strange. Can you try with qbittorrent 4.2 and make me know if anything changed?

**Comment by Owyn** [comment] 2021-11-16 16:10
I don't think anything changed...

here's bencode of torrents in stopped state in uTorrent which got started in qBitTorrent after importing btw:
![image](https://user-images.githubusercontent.com/1309656/142022123-b26bc473-af7e-4b08-832c-c91eec984986.png)

**Comment by Owyn** [comment] 2021-11-16 16:26
And here's the bencode of file which was set as "100% finished" in uTorrent but became 0% "missing files" after importing to QBT
![image](https://user-images.githubusercontent.com/1309656/142024869-6355b610-2789-4341-8784-0d862d2c6683.png)

**Comment by Owyn** [comment] 2021-11-16 20:43
and it seems it can't carry over magnet links? is there no way?
`8268/8268 Can't decode torrent file V:\UP\Soft\uTorrent\magnet:?xt=urn:btih:769251...`

**Comment by Owyn** [comment] 2021-11-17 10:40
Tried again from clean 4.2.1 install, nope - seems to be impossible to migrate my 100% finished torrents with no files, cuz qbittorrent is checking everything like it's trying to kill the HDD with it's load... "checking", "checking resume data" etc,
3k torrents are already "missing files", rest to come, while in uTorrent everything was fine (I fixed all errored torrent states with bencode editor this time before importing)
![image](https://user-images.githubusercontent.com/1309656/142185527-826b9bd8-a1a6-43a0-b509-6af04998c25e.png)

**Comment by rumanzo** [comment] 2021-11-19 10:46
> I don't think anything changed...
> 
> here's bencode of one of torrents in stopped state in uTorrent which got started in qBitTorrent after importing btw: 

About this. I didn't expect that started may be 3 (because documentation for utorrent doesn't exist). Do you have some interesting options enabled in utorrent, why started 3?


> And here's the bencode of a torrent which was showing as "100% finished" in uTorrent but became 0% "missing files" after importing to QBT

Can you show (send?) me finnaly fastresume and torrent file of this example?



> and it seems it can't carry over magnet links? is there no way?

It should works, may be regression.



I will try to refactor on this weekend

**Comment by Owyn** [comment] 2021-11-19 11:59
> About this. I didn't expect that started may be 3 (because documentation for utorrent doesn't exist). Do you have some interesting options enabled in utorrent, why started 3?

Cuz probably drive letter it was on got disconnected one time, there are other errors for stopped state as well I believe, so it's better to check
`if(started != 1) // not started` or something like that to check if it is exactly started and not anything else which'd mean it's stopped

> Can you show (send?) me finnaly fastresume and torrent file of this example?
I'm almost sure it's the same way for all my finished torrents without files present on  HDD anymore

and fastresume files exist only in my `\AppData\Local\qBittorrent\BT_backup` folder with random names, and there are 16000+ files there... qBT is a real messy program it seems wow

**Comment by rumanzo** [comment] 2021-11-19 16:59
> and fastresume files exist only in my `\AppData\Local\qBittorrent\BT_backup` folder with random names, and there are 16000+ files there... qBT is a real messy program it seems wow

Fastresume files and torrent files is not with random names, it's sha1 sum from torrent info field
https://github.com/rumanzo/bt2qbt/blob/master/libtorrent/torrent.go#L223-L229

And you can find hash of any torrent file in qBittorrent
![image](https://user-images.githubusercontent.com/15186512/142661917-0c019f93-7683-4490-ad8f-88fec0d60711.png)

**Comment by rumanzo** [comment] 2021-11-21 13:00
You will have to wait. Now is the time for refractor and test coverage.
If you want to, you can help me with code, or I will ask you some examples later.

**Comment by rumanzo** [comment] 2022-03-30 21:25
Should be fixed with https://github.com/rumanzo/bt2qbt/pull/35

**Closed by rumanzo** 2022-03-30 21:25 UTC
